title: EVERMOTOR
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
favicon: images/favicon.png
logo_dark: images/logo.svg
logo_light: images/Loge 1 22222.png
hamburger_background_image: /images/leaf-light-grey.svg
bg_image_primary: /images/header.jpg
bg_image_primary_opacity: 60
bg_image_secondary: /images/leaf-light-grey.svg
bg_image_product: /images/leaf.svg
snipcart_api_key: ''
footer_text: Copyright 2021 evermotor. All rights reserved.
palette: cyan
main_menu:
  - title: Магазин
    url: /store
    style: link
    arrow: false
  - title: О нас
    url: /about
    style: link
  - title: Инфо
    url: /faq
    style: link
sass:
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
